# Book settings
title: The Practical Testing Book
author: The World
logo: logo.png

# Information about where the book exists on the web
repository:
  url: https://galilasmb.github.io/testing-book
launch_buttons:
  notebook_interface: "classic" # The interface interactive links will activate ["classic", "jupyterlab"]
  binderhub_url: "https://mybinder.org"
  colab_url: "https://colab.research.google.com"

latex:
  latex_documents:
    targetname: book.tex
